--- 
title: "Functional analysis"
author: "Bangzhuo Tong"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [assets/book.bib, assets/packages.bib]
biblio-style: apalike
link-citations: yes
always_allow_html: true
description: "Tutorial for MGS functional analysis"
---

# Introduction
This is a tutorial introducing the analysis of microbiome functional data (Including the analysis of data annotated from MetaCyc, KEGG, VFDB, SCFA, CARD, CAZY databases).

Two cohorts' MGS data were used as demo data throughout this tutorial: One cohort contains 68 samples across 43 people (Including 15 donor, 1 BRS sample and 27 GvHD patients) in GvHD project. The other cohort consist of 10 samples from 8 patients, 1 water tube and 1 BRS in Newtech project. The first cohort was used as the input data for MetaCyc database analysis and the other one was used as the input for the analysis of KEGG, VFDB, SCFA, CARD, CAZY databases.

This book includes 7 Chapters for the following 4 templates of funcitonal analysis:

* Analysis of Metacyc data

* Analysis of KEGG data

* Analysis of target database data

* MSEA

Chapter1 introduces basic information of this tutorial.

Chapter2 introduces the analysis of Metacyc data.

Chapter3 introduces the preprocesssing (How to merge data of multiple samples and convert kegg genes to kegg pathways, etc,.) of KEGG data.

Chapter4 introduces the analysis of processed KEGG data.

Chapter5 introduces the preprocesssing (How to merge data of multiple samples) of VFDB, SCFA, CARD, CAZY data.

Chapter6 introduces the analysis of processed CARD data.

Chapter7 introduces MSEA.

